hwdec=auto-safe

sub-auto=fuzzy
sub-bold=yes

# Stolen from yt-dlp
user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36"

ytdl-format=ytdl

[loopdeloop]
profile-desc=Loop very short files
profile-cond=duration < 30
loop=inf
